import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  offlineBanner: {
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  offlineBannerText: {
    fontSize: 12,
    fontWeight: '700',
    flex: 1,
  },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    flexWrap: 'wrap',
  },
  filterChip: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: '#d1d5db',
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  filterChipText: {
    fontSize: 12,
    fontWeight: '800',
  },
  horizontalListHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  horizontalListTitle: {
    fontSize: 16,
    fontWeight: '900',
  },
  horizontalListHint: {
    fontSize: 12,
    fontWeight: '600',
  },
  horizontalListContent: {
    paddingRight: 18,
    gap: 14,
  },
  ticketCard: {
    position: 'relative',
    borderRadius: 22,
    marginBottom: 2,
  },
  horizontalTicketCard: {
    width: 336,
    marginBottom: 14,
  },
  horizontalTicketCardActive: {
    transform: [{ scale: 1.01 }],
    borderWidth: 2,
    borderColor: '#16a34a',
  },
  ticketShadow: {
    position: 'absolute',
    top: 10,
    left: 6,
    right: 6,
    bottom: -2,
    borderRadius: 20,
    backgroundColor: '#9f967e',
    opacity: 0.45,
  },
  ticketBody: {
    flexDirection: 'row',
    borderRadius: 22,
    overflow: 'hidden',
    minHeight: 178,
    backgroundColor: '#14b8a6',
  },
  ticketLeftPanel: {
    flex: 1.45,
    backgroundColor: '#11b1a7',
    paddingHorizontal: 18,
    paddingVertical: 16,
    justifyContent: 'space-between',
  },
  ticketRightPanel: {
    width: 122,
    backgroundColor: '#ffca14',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 14,
    paddingHorizontal: 10,
  },
  ticketDivider: {
    width: 18,
    backgroundColor: '#ffca14',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 20,
  },
  ticketPunchTop: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#f2ead3',
    marginLeft: -22,
  },
  ticketPunchBottom: {
    width: 26,
    height: 26,
    borderRadius: 13,
    backgroundColor: '#f2ead3',
    marginLeft: -22,
  },
  ticketHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 12,
  },
  ticketRefBlock: {
    flex: 1,
    paddingRight: 8,
  },
  ticketEyebrow: {
    color: '#d5fffb',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1.1,
  },
  ticketRef: {
    color: '#ffffff',
    fontSize: 22,
    fontWeight: '900',
    marginTop: 4,
  },
  ticketStatusBadge: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  ticketStatusText: {
    fontSize: 11,
    fontWeight: '900',
    textTransform: 'uppercase',
  },
  ticketIconRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 14,
  },
  ticketMainIconWrap: {
    width: 88,
    height: 88,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  ticketMetaStack: {
    flex: 1,
    gap: 10,
  },
  ticketMetaItem: {
    gap: 3,
  },
  ticketMetaLabel: {
    color: '#c7fffb',
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  ticketMetaValue: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  ticketFooterRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
  },
  ticketTag: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    backgroundColor: '#ffe15e',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
  },
  ticketTagText: {
    color: '#0f766e',
    fontSize: 11,
    fontWeight: '800',
  },
  ticketArrowWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  ticketArrowText: {
    color: '#ffffff',
    fontSize: 12,
    fontWeight: '800',
  },
  ticketDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#0ea5a4',
    alignSelf: 'flex-start',
    marginLeft: 8,
  },
  ticketAmountPill: {
    backgroundColor: '#5b1d2c',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 12,
    minWidth: 84,
    alignItems: 'center',
  },
  ticketAmountText: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
    textAlign: 'center',
  },
  ticketExpiryBlock: {
    alignItems: 'center',
    gap: 2,
  },
  ticketExpiryLabel: {
    color: '#6d4420',
    fontSize: 10,
    fontWeight: '800',
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  ticketExpiryValue: {
    color: '#5b1d2c',
    fontSize: 12,
    fontWeight: '900',
    textAlign: 'center',
  },
  ticketMiniBadge: {
    backgroundColor: 'rgba(91,29,44,0.08)',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  ticketMiniBadgeText: {
    color: '#5b1d2c',
    fontSize: 10,
    fontWeight: '800',
  },
  detailPanel: {
    borderRadius: 22,
    padding: 18,
    borderWidth: 1,
    gap: 16,
  },
  detailHeaderRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    gap: 12,
  },
  detailTitle: {
    fontSize: 17,
    fontWeight: '900',
  },
  detailSubtitle: {
    marginTop: 4,
    fontSize: 13,
    fontWeight: '600',
  },
  detailGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  detailCell: {
    width: '47%',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: '#f8fafc',
  },
  detailLabel: {
    fontSize: 11,
    fontWeight: '700',
    textTransform: 'uppercase',
  },
  detailValue: {
    marginTop: 4,
    fontSize: 14,
    fontWeight: '800',
  },
  detailActionButton: {
    alignSelf: 'flex-start',
  },
});

export default styles;
